import React from 'react'
import Link from 'next/link'

export default function Home() {
        return (
            <div className="main-content">
        <title>Privacy Policy</title>
        {/* Spotlight */}
        <section className="slice slice-lg bg-gradient-primary" data-offset-top="#header-main">
          <div className="container pt-5">
            <div className="row">
              <div className="col-lg-8">
                <h2 className="display-4 text-white">Privacy</h2>
                <h5 className="mb-4 text-white">Read about our privacy policy</h5>
              </div>
            </div>
          </div>
          <a href="#sct-faq" className="tongue tongue-bottom tongue-section-primary scroll-me">
            <i className="fas fa-angle-down" />
          </a>
        </section>
        <section className="slice slice-lg" id="sct-faq">
          <div className="container pt-4">
            <p>Beatact (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Beatact.</p>
            <p>This Privacy Policy applies to our website, Beatact, and its associated subdomains (collectively, our “Service”) alongside our application, Beatact. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Meanings</strong></h1>
            <p>For this Privacy Policy:</p>
            <ul>
              <li><strong>User or “You”</strong> is referred to the person who accessed the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)</li>
              <li><strong>Website</strong> is referred to Beatact, accessible from “www.beatact.net"</li>
              <li><strong>Service</strong> is referred to the app.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Third-party Social Media Service</strong> could be any website or social network website in which a User can log in or create an account to use the Service.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Cookies</strong> are a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.</li>
              <li><strong>Device</strong> could be any device with an internet connection who can access the service such as a mobile phone, a computer or a digital tablet.</li>
              <li><strong>Usage Data</strong> refers to the data that’s been collected automatically, either generated by the use of the Service or from the Service infrastructure itself. For example, how many times the user accessed the app.</li>
              <li><strong>Organiser</strong> is referred to a natural or legal person who organizes events (musical, cultural, artistic, sports, conferences, exhibitions, etc.) to which access is made on the basis of a ticket or subscription or natural or legal person who sells coupons with various values ​​( vouchers).</li>
              <li><strong>Consumer</strong> is referred to a natural or legal person who expresses his intention to purchase ticket (s) in order to have access to the events published by the Organizers.</li>
            </ul>
          </div>
          <div className="container pt-4">
            <h1><strong>What Information Do We Collect?</strong></h1>
            <p>We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<br /></p>
            <p>For Beatact Consumers:</p>
            <ul>
              <li>Email address</li>
              <li>Name / username</li>
              <li>Other information with which we can personally identify Users(e.g. Profile Picture).</li>
              <li>Identifiers associated with your device (e.g. IP address, Device OS)</li>
              <li>Location (GPS): Location data helps to create an accurate representation of your interests, and this can be used to bring more targeted and relevant ads to potential customers.</li>
            </ul>
            <p>For Beatact Organisers:</p>
            <ul>
              <li>Email address</li>
              <li>Name / username</li>
              <li>Other information with which we can personally identify Organisers(e.g. Profile Picture).</li>
              <li>Identifiers associated with your device (e.g. IP address, Device OS)</li>
              <li>Location (GPS): Location data helps to create an accurate representation of your interests, and this can be used to bring more targeted and relevant ads to potential customers.</li>
              <li>Information to facilitate payouts to Organisers(e.g. Bank account information)</li>
            </ul>
            <p>Organisers may ask consumers for supplementary information by virtual or physical means. Beatact does not control any such Personal Data collected by Organisers.</p>
            <p>Additionally, Beatact may request and collect Personal Data from third-party sources including but not limiting to Organisers, social media, payment processing partners, credit card issuing bank, etc.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>How Do We Use The Information We Collect?</strong></h1>
            <p>Any of the information we collect from you may be used in one of the following ways:</p>
            <ul>
              <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
              <li>To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)</li>
              <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
              <li>To process transactions</li>
              <li>To administer a contest, promotion, survey or other feature</li>
              <li>To send periodic emails</li>
            </ul>
          </div>
          <div className="container pt-4">
            <h1><strong>No sale of Personal Data</strong></h1>
            <p>Beatact will not sell Personal Data of any kind to any third party, including advertisers.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Transfer of Business</strong></h1>
            <p>In the course of conducting business, Beatact might sell or buy assets or other businesses.</p>
            <p>Personal Data may be part of the transferred assets in the event of a reorganisation, merger, or anything similar. Therefore you acknowledge and agree that any successor to or acquirer of Beatact or any of its assets will have the right to use your Personal Data and other information in accordance with the terms of this Privacy Policy.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Subsidiaries and Affiliates</strong></h1>
            <p>Your Personal data may also be shared with Beatact’s affiliates and subsidiaries for purposes consistent with the terms of this Privacy Policy. Therefore such entities will have to maintain and respect everything specified within this Privacy Policy.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Users under 17</strong></h1>
            <p>If you are aged 16 or under you have to get your parents’ / guardians’ permission prior to providing any Personal Information to Beatact.</p>
            <p>If you are a parent or guardian and discover that your child under 17 years of age has obtained an account on Beatact, then you may alert us at admin@beatact.net.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>How Do We Use Your Email Address?</strong></h1>
            <p>By submitting your email address on this app, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>How Long Do We Keep Your Information?</strong></h1>
            <p>We keep your information only so long as we need it to provide Beatact to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>How Do We Protect Your Information?</strong></h1>
            <p>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Beatact or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Governing Law</strong></h1>
            <p>The laws of RO, excluding its conflicts of law rules, shall govern this Agreement and your use of the app. Your use of the app may also be subject to other local, state, national, or international laws.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Your Consent</strong></h1>
            <p>By using our site, registering an account, or making a purchase, you consent to this Privacy Policy.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Links to Other Websites</strong></h1>
            <p>Our service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Cookies</strong></h1>
            <p>Beatact uses "Cookies" to identify the areas of our app that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our app. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our app correctly or at all. We never place Personally Identifiable Information in Cookies.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Payment Details</strong><br /></h1>
            <p>In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Changes To Our Privacy Policy</strong></h1>
            <p>If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Third-Party Services</strong></h1>
            <p>We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").</p>
            <p>You acknowledge and agree that Beatact shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Beatact does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</p>
            <p>Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Information Regarding Your Data Protection Rights Under General Data Protection Regulation (GDPR)</strong></h1>
            <p>For the purpose of this Privacy Policy, we are a Data Controller of your personal information.</p>
            <p>If you are from the European Economic Area (EEA), our legal basis for collecting and using your personal information, as described in this Privacy Policy, depends on the information we collect and the specific context in which we collect it. We may process your personal information because:</p>
            <ul>
              <li>We need to perform a contract with you, such as when you use our services</li>
              <li>You have given us permission to do so</li>
              <li>The processing is in our legitimate interests and it's not overridden by your rights</li>
              <li>For payment processing purposes</li>
              <li>To comply with the law</li>
            </ul>
            <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. In certain circumstances, you have the following data protection rights:</p>
            <ul>
              <li>The right to access, update or to delete the personal information we have on you</li>
              <li>The right of rectification</li>
              <li>The right to object</li>
              <li>The right of restriction</li>
              <li>The right to data portability</li>
              <li>The right to withdraw consent</li>
            </ul>
            <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
            <p>You have the right to complain to a Data Protection Authority about our collection and use of your personal information. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
          </div>
          <div className="container pt-4">
            <h1><strong>Contact Us</strong></h1>
            <p>Don't hesitate to contact us if you have any questions.</p>
            <ul>
              <li>Via Email: admin@beatact.net</li>
              <li>Via Phone Number: +40741252315</li>
            </ul>
          </div>
        </section>
        {/* Call to action (v5) */}
      </div>
        )
}
