import React from 'react'
import Link from 'next/link'

export default function Home() {
        return (
            <div className="main-content">
        <title>Terms and Conditions</title>
        {/* Spotlight */}
        <section className="slice slice-lg bg-gradient-primary" data-offset-top="#header-main">
          <div className="container pt-5">
            <div className="row">
              <div className="col-lg-8">
                <h2 className="display-4 text-white">Terms &amp; conditions</h2>
                <h5 className="mb-4 text-white">Read about your obligations while using Beatact</h5>
              </div>
            </div>
          </div>
          <a href="#sct-faq" className="tongue tongue-bottom tongue-section-primary scroll-me">
            <i className="fas fa-angle-down" />
          </a>
        </section>
        <section className="slice slice-lg" id="sct-faq">
          <div className="container pt-4">
            <h1><strong>License</strong><br /></h1>
            <p>Beatact grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the App strictly in accordance with the terms of this Agreement.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Meanings</strong><br /></h1>
            <p>For this Privacy Policy:<br /></p>
            <ul>
              <li><strong>User or “You”</strong> is referred to the person (s) who accessed the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.<br /></li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)<br /></li>
              <li><strong>Website</strong> or Site is referred to Beatact, accessible from “www.beatact.net”<br /></li>
              <li><strong>Service</strong> is referred to the app.<br /></li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.<br /></li>
              <li><strong>Third-party Social Media Service</strong> could be any website or social network website in which a User can log in or create an account to use the Service.<br /></li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.<br /></li>
              <li><strong>Cookies</strong> are a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.<br /></li>
              <li><strong>Device</strong> could be any device with an internet connection who can access the service such as a mobile phone, a computer or a digital tablet.<br /></li>
              <li><strong>Usage Data</strong> refers to the data that’s been collected automatically, either generated by the use of the Service or from the Service infrastructure itself. For example, how many times the user accessed the app.<br /></li>
              <li><strong>Organiser</strong> is referred to a natural or legal person who organizes events (musical, cultural, artistic, sports, conferences, exhibitions, etc.) to which access is made on the basis of a ticket or subscription or natural or legal person who sells coupons with various values ​​( vouchers).<br /></li>
              <li><strong>Consumer</strong> is referred to a natural or legal person who expresses his intention to purchase ticket (s) in order to have access to the events published by the Organizers.<br /></li>
              <li><strong>App </strong>is the software developed and improved from time to time by Beatact under the name ”_____”.<br /></li>
            </ul>
          </div>
          <div className="container pt-4">
            <h1><strong>Service Descriptions</strong><br /></h1>
            <p>Beatact provides the following services:<br /></p>
            <ul>
              <li>Displaying and listing events as submitted by the Organizer<br /></li>
              <li>Accepting and processing on­line orders for tickets issued by the Organizer for the event. The contract for the event is concluded directly between Consumers and the Organizer<br /></li>
              <li>Providing Consumers with a confirmation number for their transaction and their ticket, as such ticket is issued by the Organizer<br /></li>
              <li>Assisting Consumers in discovering relevant events to attend<br /></li>
            </ul>
          </div>
          <div className="container pt-4">
            <h1><strong>License to Services</strong><br /></h1>
            <p>Beatact grants Users a limited, non-exclusive, non-transferable, revocable right to use our Services through the in their capacity as either Consumer (to discover and attend events) or Organizer (to create events and sell tickets). Organizers’ and Consumers’ use of the Services must comply with these Terms and any applicable laws.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Restrictions</strong><br /></h1>
            <p>You agree not to, and you will not permit others to:<br /></p>
            <ul>
              <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the App or make the platform available to any third party.<br /></li>
              <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the App.<br /></li>
              <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Beatact or its affiliates, partners, suppliers or the licensors of the App.<br /></li>
            </ul>
          </div>
          <div className="container pt-4">
            <h1><strong>Copyrights &amp; Intellectual Property</strong><br /></h1>
            <p>Users agree that all App and Site Content may be protected by copyrights, trademarks, or other intellectual property laws. Beatact may own the Site Content or portions of the Site Content may be made available to Beatact through arrangements with third parties. Site Content included in or made available through the Services is the exclusive property of Beatact and is protected by copyright laws. Users agree to use the Site Content only for purposes permitted by these Terms and any applicable laws. Any rights not expressly granted herein are reserved.<br /><br />If you are a copyright owner or represent a copyright owner and you believe that any content within Beatact( Website or Mobile Application) infringes your Copyrights or Intellectual Property don’t hesitate to contact us at admin@Beatact.net&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Trademarks</strong><br /></h1>
            <p><br />The trademarks, service marks and logos of Beatact used in connection with the Services are registered and unregistered trademarks or service marks of Beatact. Other company, product, and service names used in connection with the Services may be trademarks or service marks owned by third parties. Users do not have license or right to use any displayed Trademark without prior written consent of Beatact. The Trademarks may not be used to disparage Beatact or any third party or in a manner that may damage any goodwill in the Trademarks. Use of any Trademarks as part of a link to or from any site is prohibited without Beatact’s prior written consent. All goodwill generated from the use of any Beatact Trademark will inure to Beatact's benefit. A number of issued and pending patents apply to the Services. Site Content may also be protected by copyrights owned by Beatact and/or third parties. Users that copy portions of the Services are in violation of these patent rights and copyrights.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Payment</strong><br /></h1>
            <p>If you register to any of our recurring payment plans, you agree to pay all fees or charges to your account for the Service in accordance with the fees, charges and billing terms in effect at the time that each fee or charge is due and payable. Unless otherwise indicated in an order form, you must provide Beatact with a valid payment method (Visa, MasterCard, or any other issuer accepted by us) (“Payment Provider”) as a condition to signing up for the Monthly plan. Your Payment Provider agreement governs your use of the designated credit card account, and you must refer to that agreement and not these Terms to determine your rights and liabilities with respect to your Payment Provider. By providing Beatact with your credit card number and associated payment information, you agree that Beatact is authorized to verify information immediately, and subsequently invoice your account for all fees and charges due and payable to Beatact hereunder and that no additional notice or consent is required. You agree to immediately notify Beatact of any change in your billing address or the credit card used for payment hereunder. Beatact reserves the right at any time to change its prices and billing methods, either immediately upon posting on our Site or by e-mail delivery to your organization’s administrator(s).<br /><br />Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed amounts shall be the responsibility of and paid for by you.<br /><br />No contract will exist between you and Beatact for the Service until Beatact accepts your order by a confirmatory e-mail, SMS/MMS message, or other appropriate means of communication.<br /><br />You are responsible for any third-party fees that you may incur when using the Service.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Fees</strong><br /></h1>
            <p>The sale of tickets carries a fee. Fees may vary based on individual agreements between Beatact and Certain Organisers. Consumers may also be charged fees other than Beatact’s fees including but not limited to applicable taxes, etc. Therefore, the total fee payed by the Consumer may vary.<br /><br />Beatact does not have any control over fees charged by an individual’s User bank or credit card company. Therefore Users should check with their bank or credit card company in order to understand all applicable fees, surcharges, and currency conversion rates prior to making any transaction on Beatact.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Return and Refund Policy</strong><br /></h1>
            <p>Thank you for using our services. We hope you are happy with your purchase. However, if you are not completely satisfied with your purchase for any reason, you may need to contact the Organiser of the event due to the fact that all ticket transactions are made between an Organiser and respective Consumer. Therefore you may need to contact the applicable Organiser in order to request a refund, as the Contract for the purchase is concluded directly between you and the Service Provider. <br /><br />Even if a refund is issued by Organiser, Beatact’s Fees will be deducted from the refund amount. Acceptance of refunds is determined by the event’s own refund policy. Thereby the Customer is responsible to check the policy with the Organiser prior to purchasing a ticket.<br /><br />In case of a cancellation or termination of an event due to a breach of contract, the Organiser will inform the User and will refund to the User the ticket price minus(-) transaction fee and the Beatact Fee.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Ticket Transfers</strong><br /></h1>
            <p>Tickets are assigned per User so transferring of tickets within Beatact to another User is not possible. Although group offers may be made by Organisers but the Ticket will still be available to only one User within Beatact. <br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Your Consent</strong><br /></h1>
            <p>By using our App or Website, you irrevocably consent to this Terms &amp; Conditions even you are not registering an account, or making a purchase,. Furthermore, you hereby confirm that by using our App or Website you have read and fully understood the entire legal meaning of the Terms &amp; Conditions. <br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Beatact User Accounts</strong><br /></h1>
            <p>Beatact requires Users to register for an account in order to access certain features and functionality. Users agree to follow certain rules when creating an account, including the following:<br /></p>
            <ol>
              <li>You agree to follow all applicable laws when creating an account.<br /></li>
              <li>You agree to provide accurate information about yourself or the entity you use the Services on behalf of. You also agree to update this information if it changes.<br /></li>
              <li>If there is a dispute about account ownership between people or entities, Beatact and its legal team will be the sole arbiter of such dispute. Beatact's decision will be final and binding on all parties and may include suspension or termination of the account in question.<br /></li>
              <li>&nbsp;If you are using the Services on behalf of a company or other entity, we expect that you have the authority to legally bind that entity and grant all permissions and licenses provided in these Terms.<br /></li>
              <li>Users agree to promptly notify Beatact in case of any unauthorised use of their account or any other breach of security. Users are responsible and will be held accountable for any activity occurring under their account.<br /></li>
            </ol>
          </div>
          <div className="container pt-4">
            <h1><strong>Beatact Organisers</strong><br /></h1>
            <p>As a Beatact Organiser, you warrant us that:<br /></p>
            <ol>
              <li>You acknowledge that Beatact and the App and the Site are only putting in connection you and the Consumers so all legal relationships related to the purchase of tickets to the events and any ancillary services are borne directly between you and the Consummers.<br /></li>
              <li>You and your affiliates are responsible for obtaining, before the start of ticket sales, all the needed permits, authorisations and licenses(“Licensure”) in regards to the applicable laws with respect to your event.<br /></li>
              <li>You and your affiliates are responsible for the fiscalization of your event. This includes providing Consumers with a receipt or a fiscal invoice. <br /></li>
              <li>You and your affiliates are responsible for any taxes in regards to the applicable laws.<br /></li>
              <li>You and your affiliates will ensure that the venue where the event is held will comply to all applicable laws.<br /></li>
              <li>You have obtained all applicable Licensures required for your event, prior to listing the event on Beatact. <br /></li>
              <li>You hereby agree to release Beatact from all damages or problems caused that are in any way connected to your or your affiliates’ Licensure or the failure to obtain or maintain any Licensure.<br /></li>
              <li>You hereby agree to release Beatact from all damages or problems caused that are in any way connected to your or your affiliates’ failure to comply with the applicable tax laws.<br /></li>
              <li>Upon the request of Beatact, you agree to provide the evidence of the aforementioned Licensure, at any point in time.<br /></li>
            </ol>
            <p>Failure to comply with any of the aforementioned clauses will result in the instant termination of your Organiser account and the cancellation of any events listed by the said Organiser.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>User and Organiser Content</strong><br /></h1>
            <p>All Content is the sole responsibility of the person from whom such Content originated. Beatact does not control, and is not responsible for user­ submitted Content and that by using the Website, You may be exposed to Content that is offensive, indecent, inaccurate, misleading, or otherwise objectionable. Furthermore, the Site may contain links to other websites, which are completely independent of Beatact.<br /><br />We make no representation or warranty as to the accuracy, completeness or authenticity of the information contained in any linked Site. Likewise, Beatact makes no representation or warranty as to the accuracy, completeness or authenticity of the information contained in any such Content posted on, transmitted through, and available through the Site.<br /><br />Users of the Site bear all risks associated with the use and/or reliance upon any Content, and/or the representations made therein, and under no circumstances will Beatact be liable in any way for any Content or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed or otherwise made available via the Site.<br /><br />You acknowledge that Beatact does not pre­screen or approve Content prior to posting. Beatact makes no representations and/or warranties to any of the claims made in any posting on reviews and comments, personal profile, listings, postings, descriptions, messages, group discussions, guides, and message boards or otherwise of any Content, by any user.<br /><br />And further, as to Content: (i) You understand and agree that Beatact may review and delete any Content that in the sole judgment of Beatact violates this Agreement or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of others; (ii) You are solely responsible for the Content that You publish or display; and (iii) by posting Content to any public area of the Site, You automatically grant, and You represent and warrant that You have the right to grant, to Beatact an irrevocable, perpetual, non-­exclusive, fully paid, worldwide license to use, copy, perform, display, and distribute such information and content and to prepare derivative works of,<br />or incorporate into other works, such information and content, and to grant and authorise sublicenses of the foregoing.<br /><br />Beatact reserves the right to investigate and take appropriate legal action in its sole discretion against anyone who violates this provision, including without limitation, removing the offending communication from the Site and terminating the membership of such violators. The following is a partial list of the kind of Content that is illegal or prohibited on the Site:<br /><br />Content that (a) is patently offensive to the online community, such as Content that promotes racism, bigotry, hatred or physical harm of any kind against any group or individual; (b) harasses or advocates harassment of another person; (c) involves the transmission of \"junk mail", "chain letters," or unsolicited mass mailing or "spamming"; (d) promotes information that You know is false, misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous; (e) promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacturer-­installed copy­protect devices, or providing pirated music or links to pirated music files; (f) contains restricted or password only access pages, or hidden pages or images (those not linked to or from another accessible page); (g) displays pornographic or sexually explicit material of any kind; (h) provides material that exploits people under the age of 18 in a sexual or violent manner, or solicits personal information from anyone under 18; (i) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses; (j) solicits passwords or personal identifying information for commercial or unlawful purposes from other users; (k) engages in commercial activities and/or sales without our prior written consent such as contests, sweepstakes, barter, advertising, and pyramid schemes; or (l) post non­local or otherwise irrelevant Content, repeatedly post the same or similar Content or otherwise impose an unreasonable or disproportionately large load on our infrastructure. Even though all of this is strictly prohibited, there is a small chance that You might become exposed to such items and You further waive Your right to any damages (from any party) related to such exposure.<br /><br /><br /><br /><br /><br />Beatact may use a User’s name, logo and event picture, as well as any other information to identify them as a Beatact customer both on the Services and in promotional materials.<br /><br />Beatact may preserve User Content and account information and disclose these if required to do so by law, to comply with legal process, to respond to claims that any User Content violates the rights of third parties, to enforce these Terms, or to protect the rights and safety of Beatact, its users, and its representatives.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Links to Other Websites</strong><br /></h1>
            <p>Our service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Terms &amp; Conditions of every site You visit.<br /><br />We have no control over and assume no responsibility for the content, Terms &amp; Conditions or practices of any third party sites or services.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Cookies</strong><br /></h1>
            <p>Beatact uses "Cookies" to identify the areas of our app that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our app. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access some functionality on our app correctly or at all. We never place Personally Identifiable Information in Cookies. By using our site, registering an account, or making a purchase, you consent to the fact that we use cookies.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Changes To Our Terms &amp; Conditions</strong><br /></h1>
            <p>You acknowledge and agree that Beatact may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at Beatact’s sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform Beatact when you stop using the Service. You acknowledge and agree that if Beatact disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.<br /><br />If we decide to change our Terms &amp; Conditions, we will post those changes on this page, and/or update the Terms &amp; Conditions modification date below.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Modifications to Our app</strong><br /></h1>
            <p>Beatact reserves the right to modify, suspend or discontinue, temporarily or permanently, the app or any service to which it connects, with or without notice and without liability to you.<br /><br />The modifications may alter the use of the App or of the Site and will depend on the hardware used by the User, with no obligation of us to make it available on certain platform (s) or to ensure the compatibility with some device (s).<br /><br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Updates to Our app</strong><br /></h1>
            <p>Beatact may from time to time provide enhancements or improvements to the features/ functionality of the app, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").<br /><br />Updates may modify or delete certain features and/or functionalities of the app. You agree that Beatact has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the app to you or (iii) adapt the App to any hardware or device specifications.<br /><br />You further agree that all Updates will be (i) deemed to constitute an integral part of the app, and (ii) subject to the terms and conditions of this Agreement.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Linked Accounts &amp; Third-Party Services</strong><br /></h1>
            <p>We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").<br /><br />You acknowledge and agree that Beatact shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Beatact does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.<br /><br />Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Force Majeure</strong><br /></h1>
            <p>Beatact shall not be responsible for any delay in, or failure of, the Service due to any occurrence commonly known as “force majeure,” including war, riots, terrorism, pandemic, or other concerted acts of workmen casualties or accidents, or any other causes, circumstances, or contingencies beyond Beatact’s, which prevent or hinder the performance of Beatact of any of its obligations hereunder.<br /><br />Relief from Liability. A Party (an Affected Party) shall be relieved from liability (except for any accrued payment obligations) for any delay in the performance of, or inability to perform, an obligation under this Agreement which is directly caused by or results from a Force Majeure Event, for so long as the inability to perform continues. <br /><br />Obligations of Affected Party. Notwithstanding the foregoing, the Affected Party shall:<br /></p>
            <ul className="list-unstyled">
              <li>(i)&nbsp; make all reasonable efforts to prevent, minimise and thereafter mitigate any delays or costs occasioned by any Force Majeure Event, including recourse to alternative acceptable sources of services; and<br /></li>
              <li>(ii)&nbsp; use all reasonable efforts to ensure resumption of normal performance of the Services after the occurrence of any Force Majeure Event and perform its obligations hereunder to the maximum extent practicable.<br /></li>
            </ul>
            <p>Each Party shall bear their respective costs and neither Party shall be required to pay to the other Party any costs arising out of a Force Majeure Event.<br /><br />A Force Majeure Event means any event or circumstance or combination of events whenever occurring which is directly caused by or results from an event described hereinbelow for so long as such event or the inability to perform continues, and:<br /></p>
            <ul className="list-unstyled">
              <li>(i)&nbsp; is outside the control of the Affected Party;<br /></li>
              <li>(ii)&nbsp; could not be avoided, prevented or overcome with reasonable foresight, prudence and diligence or otherwise by taking action according to Good Industry Practice; and<br /></li>
              <li>(iii)&nbsp; materially prevents, hinders or delays performance of all or a material part of the Affected Party’s obligations.<br /></li>
            </ul>
            <p>Categories of Force Majeure Events<br /><br />A Force Majeure Event shall include, but not be limited to, the following categories or circumstances of a natural or general nature, including:<br /></p>
            <ul>
              <li>acts of God;<br /></li>
              <li>nuclear explosion, radioactive, biological or chemical contamination;<br /></li>
              <li>landslides, earthquakes and tsunamis;<br /></li>
              <li>epidemic, plague or quarantine;<br /></li>
              <li>blockade or closure of cities;<br /></li>
              <li>strikes or other industrial action affecting the Services;<br /></li>
              <li>war (whether declared or not), civil war, invasion, embargo, military coup, revolution or armed conflict on a national scale;<br /></li>
              <li>sabotage, criminal damage, terrorism, but only when any of the Services are directly affected;<br /></li>
              <li>riot, civil commotion, insurrection on a massive or national scale; and<br /></li>
              <li>adverse weather conditions.<br /></li>
            </ul>
          </div>
          <div className="container pt-4">
            <h1><strong>Term and Termination</strong><br /></h1>
            <p>This Agreement shall remain in effect until terminated by you or Beatact.<br /><br />Beatact may, in its sole discretion, at any time and for any or no reason, suspend or<br />terminate this Agreement with or without prior notice.<br /><br />This Agreement will terminate immediately, without prior notice from Beatact, in the<br />event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the app and all copies thereof from your computer.<br /><br />Upon termination of this Agreement, you shall cease all use of the app and delete all copies of the app from your computer.<br /><br />Termination of this Agreement will not limit any of Beatact's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Indemnification</strong><br /></h1>
            <p>You agree to indemnify and hold Beatact and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the app; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>No Warranties</strong><br /></h1>
            <p>The app is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Beatact, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers,<br />expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the app, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, Beatact provides no warranty or undertaking, and makes no representation of any kind that the app will meet your requirements, achieve any intended results, be compatible or work with any other software, apps, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.<br /><br />Without limiting the foregoing, neither Beatact nor any Beatact's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the app, or the information, content, and materials or products included thereon; (ii) that the app will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the app; or (iv) that the app, its servers, the content, or e-mails sent from or on behalf of Beatact are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.<br /><br />Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Limitation of Liability</strong><br /></h1>
            <p>Notwithstanding any damages that you might incur, the entire liability of Beatact and any of<br />its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the app.<br /><br />To the maximum extent permitted by applicable law, in no event shall Beatact or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the app, third-party software and/or third-party hardware used with the app, or otherwise in connection with any provision of this Agreement), even if Beatact or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.<br /><br />Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Severability</strong><br /></h1>
            <p>If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Waiver</strong><br /></h1>
            <p>Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not affect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Amendments to this Agreement</strong><br /></h1>
            <p>Beatact reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.<br /><br />By continuing to access or use our app after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Beatact.<br /><br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Entire Agreement</strong><br /></h1>
            <p>The Agreement constitutes the entire agreement between you and Beatact regarding your use of the app and supersedes all prior and contemporaneous written or oral agreements between you and Beatact.<br /><br />You may be subject to additional terms and conditions that apply when you use or purchase other Beatact's services, which Beatact will provide to you at the time of such use or purchase.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Disclaimer</strong><br /></h1>
            <p>Beatact is not responsible for any content, code or any other imprecision.<br /><br />Beatact does not provide warranties or guarantees.<br /><br />In no event shall Beatact be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.<br /></p>
          </div>
          <div className="container pt-4">
            <h1><strong>Contact Us</strong><br /></h1>
            <p>Don't hesitate to contact us if you have any questions.<br /></p>
            <ul>
              <li>Via Email: admin@Beatact.net<br /></li>
              <li>Via Phone Number: +40741252315<br /></li>
            </ul>
          </div>
        </section>
        {/* Call to action (v5) */}
      </div>
        )
}
